# Generated by Django 5.2.15 on 2026-07-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='items_item_locatio_81e8aa_gist',
            old_name='items_item_locatio_gist_idx',
        ),
    ]
